# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'eric@commercekitchen.com'
  config.password       = 'fSQ-8$?^3_H9faY#BnJR=Qq#VHH2?-@-'
  config.integrator_key = 'COMM-e3adeeb4-8021-4e4f-a8e6-f17484e330b5'
  config.account_id     = '1ced966b-8c18-4507-bbc2-dda4514813f4'
  # config.endpoint       = 'https://www.docusign.net/restapi'
  # config.api_version    = 'v2'
end
